name: Deploy to AWS S3 and CloudFront

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: us-east-1 # Change this to your preferred region

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: |
          # First, sync all files except clean URL files
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET }} --delete --exclude "services" --exclude "about" --exclude "contact"
          
          # Then upload clean URL files with proper MIME type
          if [ -f "dist/services" ]; then
            aws s3 cp dist/services s3://${{ secrets.S3_BUCKET }}/services --content-type "text/html" --cache-control "public, max-age=31536000"
          fi
          
          if [ -f "dist/about" ]; then
            aws s3 cp dist/about s3://${{ secrets.S3_BUCKET }}/about --content-type "text/html" --cache-control "public, max-age=31536000"
          fi
          
          if [ -f "dist/contact" ]; then
            aws s3 cp dist/contact s3://${{ secrets.S3_BUCKET }}/contact --content-type "text/html" --cache-control "public, max-age=31536000"
          fi

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
